### ISSUE TITLE
Puts me as another user

### ISSUE THREAD

**Issue by eloicote** [JayJay1989/GameSenseSDK#8]
When I installed this mod my account suddenly turned to an account named Elina_Fox132

**Comment by JayJay1989** [comment]
DONT REMOVE THE TEMPLATE OF THE BUGREPORT, its there for a reason.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Logs/crashlogs/etc**
use https://gist.github.com and link it below

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.
upload to imgur and link it below

**Minecraft enviroment (please complete the following information):**
 - OS: [e.g. Windows/Linux/MacOS]
 - Ram allocated [e.g. 8G]
 - Minecraft & Forge version [e.g. 1.12.2 - 14.23.5.2772]
 - Mod Version [e.g. 1.12.6]


**Additional context**
Add any other context about the problem here.
